<?php
include 'config.php';

function search($search) {
    try {
        $db = new PDO(
            "mysql:host=" . DBHOST . "; dbname=" . DBNAME . ";charset=utf8",
            DBUSER,
            DBPASS
        );

        $select_query = "
            SELECT 'user' AS table_name, user_id AS id, first_name AS attribute1, last_name AS attribute2, email AS attribute3
            FROM user
            WHERE first_name LIKE \"%{$search}%\" OR last_name LIKE \"%{$search}%\" OR email LIKE \"%{$search}%\"
            UNION
            SELECT 'website' AS table_name, site_id AS id, site_name AS attribute1, domain AS attribute2, NULL AS attribute3
            FROM website
            WHERE site_name LIKE \"%{$search}%\" OR domain LIKE \"%{$search}%\"
            UNION
            SELECT 'password' AS table_name, user_id AS id, site_id AS attribute1, username AS attribute2, comment AS attribute3
            FROM password
            WHERE username LIKE \"%{$search}%\" OR comment LIKE \"%{$search}%\"
        ";
        $statement = $db -> prepare($select_query);
        $statement -> execute();

        if (count($statement -> fetchAll()) == 0) {
            return 0;
        } else {
            echo "      <table>\n";
            echo "        <thead>\n";
            echo "          <tr>\n";
            echo "            <th>Table</th>\n";
            echo "            <th>ID</th>\n";
            echo "            <th>Attribute 1</th>\n";
            echo "            <th>Attribute 2</th>\n";
            echo "            <th>Attribute 3</th>\n";
            echo "          </tr>\n";
            echo "        </thead>\n";
            echo "        <tbody>\n";

            // Populate the table with data coming from the database...
            foreach ($db ->query($select_query) as $row) {
                echo "          <tr>\n";
                echo "            <td>" . htmlspecialchars($row['table_name']) . "</td>\n";
                echo "            <td>" . htmlspecialchars($row['id']) . "</td>\n";
                echo "            <td>" . htmlspecialchars($row['attribute1']) . "</td>\n";
                echo "            <td>" . htmlspecialchars($row['attribute2']) . "</td>\n";
                echo "            <td>" . htmlspecialchars($row['attribute3']) . "</td>\n";
                echo "          </tr>\n";
            }

            echo "         </tbody>\n";
            echo "      </table>\n";
        }
    } catch( PDOException $e ) {
        echo '<p>The following message was generated by function <code>search</code>:</p>' . "\n";
        echo '<p id="error">' . $e -> getMessage() . '</p>' . "\n";
        echo "<p>There are a few reasons for this. Perhaps the database doesn’t exist or wasn’t mounted. Does the volume/drive containing the database have read and write permissions?</p>\n";
        echo '<p>Click <a href="./">here</a> to go back.</p>';

        exit;
    }
}

function update($current_attribute, $new_attribute, $query_attribute, $pattern) {
    try {
        $db = new PDO(
            "mysql:host=" . DBHOST . "; dbname=" . DBNAME . ";charset=utf8",
            DBUSER,
            DBPASS
        );

        $db -> query("UPDATE user SET {$current_attribute}=\"{$new_attribute}\" WHERE {$query_attribute}=\"{$pattern}\"");
    } catch( PDOException $e ) {
        echo '<p>The following message was generated by function <code>update</code>:</p>' . "\n";
        echo '<p id="error">' . $e -> getMessage() . '</p>' . "\n";

        exit;
    }
}

function insert($user_id, $first_name, $last_name, $email) {
    try {
        $db = new PDO(
            "mysql:host=" . DBHOST . "; dbname=" . DBNAME . ";charset=utf8",
            DBUSER,
            DBPASS
        );

        $statement = $db -> prepare("INSERT INTO user VALUES (:user_id, :first_name, :last_name, :email)");
        $statement -> execute(
            array(
                'user_id'    => $user_id,
                'first_name' => $first_name,
                'last_name'  => $last_name,
                'email'      => $email
            )
        );
    } catch(PDOException $e) {
        echo '<p>The following message was generated by function <code>insert</code>:</p>' . "\n";
        echo '<p id="error">' . $e -> getMessage() . '</p>' . "\n";

        exit;
    }
}

function delete($current_attribute, $pattern) {
    try {
        $db = new PDO(
            "mysql:host=" . DBHOST . "; dbname=" . DBNAME . ";charset=utf8",
            DBUSER,
            DBPASS
        );

        $db -> query("DELETE FROM user WHERE {$current_attribute}=\"{$pattern}\"");
    } catch(PDOException $e) {
        echo '<p>The following message was generated by function <code>delete</code>:</p>' . "\n";
        echo '<p id="error">' . $e -> getMessage() . '</p>' . "\n";

        exit;
    }
}
